openapi: 3.0.0
info:
  title: PACS API
  version: 1.0.0
servers:
  - url: https://user-api.example.com
    description: PACS API server

paths:
  /users/{user_id}:
    get:
      operationId: getUserData
      summary: Get user information
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: include_details
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: User data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          id: 
                            type: string
                          name:
                            type: string
                          email:
                            type: string

  /orders:
    get:
      operationId: getOrderHistory
      summary: Get user's order history
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [completed, pending, cancelled]
      responses:
        '200':
          description: Order history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        amount:
                          type: number
                        created_at:
                          type: string
                          format: date-time

    post:
      operationId: createOrder
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: string
                      quantity:
                        type: integer
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  order:
                    type: object
                    properties:
                      details:
                        type: object 